package com.example.demo

class JuegoRepository {
    companion object {
        var listaPreguntas = mutableListOf(

            Juego(0,"¿ DE QUE PAIS ES LA MARCA DE ADIDAS ? ","ESPAÑA","COLOMBIA","JAPON","ALEMANIA"),
            Juego(1,"¿ DE QUE PAIS ES EL PILOTO DE FORMULA 1 FERNANDO ALONSO ?","ESPAÑA","JAPON","COLOMBIA","ALEMANIA"),
            Juego(2,"¿ EN QUE PAIS SE HACE LA MEJOR COCAINA ?","ESPAÑA","JAPON","COLOMBIA","ALEMANIA",),
            Juego(3,"¿ EN QUE PAIS SE ENCUENTRA LA CUIDAD MAS TECNOLOGICA DEL MUNDO?","JAPON","COLOMBIA","ALEMANIA","ESPAÑA"),
            Juego(4,"¿ DE QUE PAIS ES LA MARCA NIKE ?","EE.UU","BRASIL","CHINA","REINO UNIDO"),
            Juego(5,"¿ DE QUE PAIS ES EL PILOTO MICHAEL SHUMAHER ? ","JAPON","COLOMBIA","ALEMANIA","ESPAÑA"),
            Juego(6,"¿ EN QUE PAIS ESTA LA CIUDAD DE NEW YORK ? ","EE.UU","COLOMBIA","ALEMANIA","ESPAÑA"),
            Juego(7,"¿ EN QUE PAIS SE ENCUENTRA LA CIUDAD DE LA LUZ ? ","JAPON","FRANCIA","ALEMANIA","ESPAÑA"),
            Juego(8,"¿ DE QUE PAIS ES LA FAMOSA MARCA DE COCHES FERRARI ?","JAPON","COLOMBIA","ITALIA","ESPAÑA"),
            Juego(9,"¿ DE QUE PAIS ES EL CANTANTE DADDY YANKEE ?","JAPON","COLOMBIA","ALEMANIA","PUERTO RICO")
        )

    }
}

